apiVersion: argoproj.io/vlalphal
kind: Application
metadata:
  name: default
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: envs/default
    targetRevision: main
    repoUrl: https://github.com/AlexGerus/argo-cd-envs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
